### ISSUE TITLE
cannot discover devices

### ISSUE THREAD

**Issue by carlosperate** [balloob/pywemo#5]
Hi,

I am trying to run pywemo and encountering the following issue in the python terminal:
```
Python 2.7.5 (default, May 15 2013, 22:43:36) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pywemo
>>> devices = pywemo.discover_devices()
>>> print devices
[]
>>> devices = pywemo.discover_devices()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pywemo\discovery.py", line 22, in discover_devices
    device = device_from_uuid_and_location(entry.st, entry.location)
  File "pywemo\discovery.py", line 46, in device_from_uuid_and_location
    return Switch(location)
  File "pywemo\ouimeaux_device\__init__.py", line 32, in __init__
    service = Service(self, svc, base_url)
  File "pywemo\ouimeaux_device\api\service.py", line 80, in __init__
    for action in self._svc_config.get_action():
AttributeError: 'NoneType' object has no attribute 'get_action'
>>>
```
I currently have no issues discovery my Wemo switch with the ouimeaux package (although I have only tested it using these procedures http://ouimeaux.readthedocs.org/en/latest/api.html) . Any ideas what could be causing this?

**Comment by carlosperate** [comment]
This commit https://github.com/balloob/pywemo/commit/e47eae6b22cdfcb90e3c235670c37f2d43eb1cbd from @tomwilkie 's fork seems fix my issue. Hopefully @tomwilkie can submit a pull request?

**Comment by tomwilkie** [comment]
Need to merge and rebase, but will do that today.

Thanks

Tom

**Comment by carlosperate** [comment]
Thanks Tom!

**Comment by balloob** [comment]
Sorry for the delay, I have just merged it in.
